name: Deploy dev

on:
  push:
    branches: [ main ]
    paths:
      - "dev/*"
      - "dev/**/*"
      - ".github/workflows/deploy-dev.yaml"

  workflow_dispatch:

# concurrency:
#   group: environment-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bitops
      env:
        ENVIRONMENT: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-2
        TF_STATE_BUCKET: fast-react-static-renderer-operations-dev
      run: |
        echo "running  _scripts/deploy/deploy.sh"
        ./_scripts/deploy/deploy.sh