name: Deploy dev

on:
  push:
    branches: [ main ]
    paths:
      - "dev/*"
      - "dev/**/*"
      - ".github/workflows/deploy-dev.yaml"

  workflow_dispatch:

# concurrency:
#   group: environment-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bitops
      env:
        ENVIRONMENT: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-2
        TF_STATE_BUCKET: fast-react-static-renderer-operations-dev-state

        # THIS NEEDS TO BE CHANGED IF YOU FORKED THE REPO!
        # Remove if you want to use github actions and you want a domain-less deployment
        TFVARS_AUTO_JSON: '{"domain_name": "fast-react-static-renderer.com","subdomain_name": "dev.fast-react-static-renderer.com", "hosted_zone_id": "Z09768261LFU7OL6902KA"}'
      run: |
        echo "running  _scripts/deploy/deploy.sh"
        ./_scripts/deploy/deploy.sh