name: Deploy global-tools

on:
  push:
    # TODO: remove before merge
    branches: [ optional-domain ]
    # TODO: uncomment before merge
    # branches: [ main ]
    paths:
      - "global-tools/*"
      - "global-tools/**/*"
      - ".github/workflows/deploy-global-tools.yaml"

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bitops
      env:
        ENVIRONMENT: global-tools
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-2
        TF_STATE_BUCKET: fast-react-static-renderer-operations-global-tools-state
      run: |
        echo "running  _scripts/deploy/deploy.sh"
        ./_scripts/deploy/deploy.sh